---
- name: list variable
  hosts: IOS
  gather_facts: no

  tasks:
    - name: sh list of command
      ios_command:
        commands:
          - sh ip int bri
        
      
      register: output
    - name: print all output
      ansible.builtin.debug:
        var: output
    
